### ISSUE TITLE
Arrange shadow position at Contact info & Socials.

### ISSUE THREAD

**Issue by ghost** [jerryxfu/jerrydev-reactjs#36]
The shadows ar not centered, and some the icons are out of it.

**Comment by Kedarnath-Rothe** [comment]
@AspectOfJerry  Please assign this issue to me

**Comment by jerryxfu** [comment]
![image](https://github.com/AspectOfJerry/jerrydev/assets/69355304/749c49b5-3fd9-4277-9743-0ca8fb01fc7c)
thats crazy
