### ISSUE TITLE
smoth scroll not working on chrome

### ISSUE THREAD

**Issue by ghost** [jerryxfu/jerrydev-reactjs#47]
**Describe the bug**
Navbar fragment links and return to top not applying smooth scrolling on Chrome

**Expected behavior**
Smooth scrolling on all browsers

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: latest?

**Smartphone (please complete the following information):**
 - unknown

**Comment by jerryxfu** [comment]
seems to be working for me now
